# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: i2f Alumni
# email: admin@uav.berkeley.edu
description: Alumni site for the i2f program at NASA JPL.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

collections:
  members:
    output: true
    permalink: /:collection/:name

# Logo settings
logo-image-url: images/logo.png
font-awesome-icon-logo:

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
